### ISSUE TITLE
Criação da pagina sobre.

### ISSUE THREAD

**Issue by web-fr** [tiesco-assis/github-master#3]
Vocês poderiam criar uma página sobre? Agradeço

**Comment by tiesco-assis** [comment]
A pagina está em produção.

**Comment by web-fr** [comment]
Obrigado, estou no aguardo.

 

Att.

 




FRANCISCO ASSIS


Webmaster


 

 (11) 9 7717-1255

Atendi.: segunda à sexta das 08h30 às 17h00


 <https://www.webfr.com.br/> www.webfr.com.br
